// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for the AllocateQuota method.
public struct AllocateQuotaRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the service as specified in the service configuration. For example,
  /// `"pubsub.googleapis.com"`.
  ///
  /// See [google.api.Service][google.api.Service] for the definition of a
  /// service name.
  public var serviceName: Swift.String = Swift.String()

  /// Operation that describes the quota allocation.
  public var allocateOperation: QuotaOperation? = nil

  /// Specifies which version of service configuration should be used to process
  /// the request. If unspecified or no matching version can be found, the latest
  /// one will be used.
  public var serviceConfigId: Swift.String = Swift.String()

  /// Initialize a new instance of `AllocateQuotaRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AllocateQuotaRequest().with { $0.serviceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v1.AllocateQuotaRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
