// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
import GoogleCloudWkt

/// Distribution represents a frequency distribution of double-valued sample
/// points. It contains the size of the population of sample points plus
/// additional optional information:
///
/// * the arithmetic mean of the samples
/// * the minimum and maximum of the samples
/// * the sum-squared-deviation of the samples, used to compute variance
/// * a histogram of the values of the sample points
public struct Distribution: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The total number of samples in the distribution. Must be >= 0.
  public var count: Swift.Int64 = Swift.Int64()

  /// The arithmetic mean of the samples in the distribution. If `count` is
  /// zero then this field must be zero.
  public var mean: Swift.Double = Swift.Double()

  /// The minimum of the population of values. Ignored if `count` is zero.
  public var minimum: Swift.Double = Swift.Double()

  /// The maximum of the population of values. Ignored if `count` is zero.
  public var maximum: Swift.Double = Swift.Double()

  /// The sum of squared deviations from the mean:
  ///   Sum[i=1..count]((x_i - mean)^2)
  /// where each x_i is a sample values. If `count` is zero then this field
  /// must be zero, otherwise validation of the request fails.
  public var sumOfSquaredDeviation: Swift.Double = Swift.Double()

  /// The number of samples in each histogram bucket. `bucket_counts` are
  /// optional. If present, they must sum to the `count` value.
  ///
  /// The buckets are defined below in `bucket_option`. There are N buckets.
  /// `bucket_counts[0]` is the number of samples in the underflow bucket.
  /// `bucket_counts[1]` to `bucket_counts[N-1]` are the numbers of samples
  /// in each of the finite buckets. And `bucket_counts[N]` is the number
  /// of samples in the overflow bucket. See the comments of `bucket_option`
  /// below for more details.
  ///
  /// Any suffix of trailing zeros may be omitted.
  public var bucketCounts: [Swift.Int64] = []

  /// Example points. Must be in increasing order of `value` field.
  public var exemplars: [GoogleApi.Distribution.Exemplar] = []

  /// Defines the buckets in the histogram. `bucket_option` and `bucket_counts`
  /// must be both set, or both unset.
  ///
  /// Buckets are numbered in the range of [0, N], with a total of N+1 buckets.
  /// There must be at least two buckets (a single-bucket histogram gives
  /// no information that isn't already provided by `count`).
  ///
  /// The first bucket is the underflow bucket which has a lower bound
  /// of -inf. The last bucket is the overflow bucket which has an
  /// upper bound of +inf. All other buckets (if any) are called "finite"
  /// buckets because they have finite lower and upper bounds. As described
  /// below, there are three ways to define the finite buckets.
  ///
  ///   (1) Buckets with constant width.
  ///   (2) Buckets with exponentially growing widths.
  ///   (3) Buckets with arbitrary user-provided widths.
  ///
  /// In all cases, the buckets cover the entire real number line (-inf,
  /// +inf). Bucket upper bounds are exclusive and lower bounds are
  /// inclusive. The upper bound of the underflow bucket is equal to the
  /// lower bound of the smallest finite bucket; the lower bound of the
  /// overflow bucket is equal to the upper bound of the largest finite
  /// bucket.
  public var bucketOption: OneOf_BucketOption? = nil

  /// Initialize a new instance of `Distribution`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Distribution().with { $0.count = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case count = "count"
    case mean = "mean"
    case minimum = "minimum"
    case maximum = "maximum"
    case sumOfSquaredDeviation = "sumOfSquaredDeviation"
    case bucketCounts = "bucketCounts"
    case linearBuckets = "linearBuckets"
    case exponentialBuckets = "exponentialBuckets"
    case explicitBuckets = "explicitBuckets"
    case exemplars = "exemplars"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.count = try container.decode(Swift.Int64.self, forKey: .count)
    self.mean = try container.decode(Swift.Double.self, forKey: .mean)
    self.minimum = try container.decode(Swift.Double.self, forKey: .minimum)
    self.maximum = try container.decode(Swift.Double.self, forKey: .maximum)
    self.sumOfSquaredDeviation = try container.decode(
      Swift.Double.self, forKey: .sumOfSquaredDeviation)
    self.bucketCounts = try container.decode([Swift.Int64].self, forKey: .bucketCounts)
    self.exemplars = try container.decode(
      [GoogleApi.Distribution.Exemplar].self, forKey: .exemplars)

    var bucketOption: OneOf_BucketOption? = nil
    let bucketOptionCheckAndSet = {
      if bucketOption != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'bucketOption'"))
      }
      bucketOption = $0
    }
    if let linearBuckets = try container.decodeIfPresent(
      Distribution.LinearBuckets?.self, forKey: .linearBuckets)
    {
      try bucketOptionCheckAndSet(.linearBuckets(linearBuckets))
    }
    if let exponentialBuckets = try container.decodeIfPresent(
      Distribution.ExponentialBuckets?.self, forKey: .exponentialBuckets)
    {
      try bucketOptionCheckAndSet(.exponentialBuckets(exponentialBuckets))
    }
    if let explicitBuckets = try container.decodeIfPresent(
      Distribution.ExplicitBuckets?.self, forKey: .explicitBuckets)
    {
      try bucketOptionCheckAndSet(.explicitBuckets(explicitBuckets))
    }
    self.bucketOption = bucketOption
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.count, forKey: .count)
    try container.encode(self.mean, forKey: .mean)
    try container.encode(self.minimum, forKey: .minimum)
    try container.encode(self.maximum, forKey: .maximum)
    try container.encode(self.sumOfSquaredDeviation, forKey: .sumOfSquaredDeviation)
    try container.encode(self.bucketCounts, forKey: .bucketCounts)
    try container.encode(self.exemplars, forKey: .exemplars)

    if let choice = self.bucketOption {
      switch choice {
      case .linearBuckets(let value):
        try container.encode(value, forKey: .linearBuckets)
      case .exponentialBuckets(let value):
        try container.encode(value, forKey: .exponentialBuckets)
      case .explicitBuckets(let value):
        try container.encode(value, forKey: .explicitBuckets)
      }
    }
  }

  /// Describing buckets with constant width.
  public struct LinearBuckets: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The number of finite buckets. With the underflow and overflow buckets,
    /// the total number of buckets is `num_finite_buckets` + 2.
    /// See comments on `bucket_options` for details.
    public var numFiniteBuckets: Swift.Int32 = Swift.Int32()

    /// The i'th linear bucket covers the interval
    ///   [offset + (i-1) * width, offset + i * width)
    /// where i ranges from 1 to num_finite_buckets, inclusive.
    /// Must be strictly positive.
    public var width: Swift.Double = Swift.Double()

    /// The i'th linear bucket covers the interval
    ///   [offset + (i-1) * width, offset + i * width)
    /// where i ranges from 1 to num_finite_buckets, inclusive.
    public var offset: Swift.Double = Swift.Double()

    /// Initialize a new instance of `LinearBuckets`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LinearBuckets().with { $0.numFiniteBuckets = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.servicecontrol.v1.Distribution.LinearBuckets"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Describing buckets with exponentially growing width.
  public struct ExponentialBuckets: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The number of finite buckets. With the underflow and overflow buckets,
    /// the total number of buckets is `num_finite_buckets` + 2.
    /// See comments on `bucket_options` for details.
    public var numFiniteBuckets: Swift.Int32 = Swift.Int32()

    /// The i'th exponential bucket covers the interval
    ///   [scale * growth_factor^(i-1), scale * growth_factor^i)
    /// where i ranges from 1 to num_finite_buckets inclusive.
    /// Must be larger than 1.0.
    public var growthFactor: Swift.Double = Swift.Double()

    /// The i'th exponential bucket covers the interval
    ///   [scale * growth_factor^(i-1), scale * growth_factor^i)
    /// where i ranges from 1 to num_finite_buckets inclusive.
    /// Must be > 0.
    public var scale: Swift.Double = Swift.Double()

    /// Initialize a new instance of `ExponentialBuckets`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ExponentialBuckets().with { $0.numFiniteBuckets = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.servicecontrol.v1.Distribution.ExponentialBuckets"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Describing buckets with arbitrary user-provided width.
  public struct ExplicitBuckets: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// 'bound' is a list of strictly increasing boundaries between
    /// buckets. Note that a list of length N-1 defines N buckets because
    /// of fenceposting. See comments on `bucket_options` for details.
    ///
    /// The i'th finite bucket covers the interval
    ///   [bound[i-1], bound[i])
    /// where i ranges from 1 to bound_size() - 1. Note that there are no
    /// finite buckets at all if 'bound' only contains a single element; in
    /// that special case the single bound defines the boundary between the
    /// underflow and overflow buckets.
    ///
    /// bucket number                   lower bound    upper bound
    ///  i == 0 (underflow)              -inf           bound[i]
    ///  0 < i < bound_size()            bound[i-1]     bound[i]
    ///  i == bound_size() (overflow)    bound[i-1]     +inf
    public var bounds: [Swift.Double] = []

    /// Initialize a new instance of `ExplicitBuckets`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ExplicitBuckets().with { $0.bounds = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.servicecontrol.v1.Distribution.ExplicitBuckets"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Defines the buckets in the histogram. `bucket_option` and `bucket_counts`
  /// must be both set, or both unset.
  ///
  /// Buckets are numbered in the range of [0, N], with a total of N+1 buckets.
  /// There must be at least two buckets (a single-bucket histogram gives
  /// no information that isn't already provided by `count`).
  ///
  /// The first bucket is the underflow bucket which has a lower bound
  /// of -inf. The last bucket is the overflow bucket which has an
  /// upper bound of +inf. All other buckets (if any) are called "finite"
  /// buckets because they have finite lower and upper bounds. As described
  /// below, there are three ways to define the finite buckets.
  ///
  ///   (1) Buckets with constant width.
  ///   (2) Buckets with exponentially growing widths.
  ///   (3) Buckets with arbitrary user-provided widths.
  ///
  /// In all cases, the buckets cover the entire real number line (-inf,
  /// +inf). Bucket upper bounds are exclusive and lower bounds are
  /// inclusive. The upper bound of the underflow bucket is equal to the
  /// lower bound of the smallest finite bucket; the lower bound of the
  /// overflow bucket is equal to the upper bound of the largest finite
  /// bucket.
  public enum OneOf_BucketOption: Codable, Equatable, Sendable {
    /// Buckets with constant width.
    indirect case linearBuckets(Distribution.LinearBuckets?)
    /// Buckets with exponentially growing width.
    indirect case exponentialBuckets(Distribution.ExponentialBuckets?)
    /// Buckets with arbitrary user-provided width.
    indirect case explicitBuckets(Distribution.ExplicitBuckets?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v1.Distribution"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
