// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLoggingType
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An individual log entry.
public struct LogEntry: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The log to which this log entry belongs. Examples: `"syslog"`,
  /// `"book_log"`.
  public var name: Swift.String = Swift.String()

  /// The time the event described by the log entry occurred. If
  /// omitted, defaults to operation start time.
  public var timestamp: GoogleCloudWKT.Timestamp? = nil

  /// The severity of the log entry. The default value is
  /// `LogSeverity.DEFAULT`.
  public var severity: GoogleCloudLoggingType.LogSeverity = GoogleCloudLoggingType.LogSeverity()

  /// Optional. Information about the HTTP request associated with this
  /// log entry, if applicable.
  public var httpRequest: HttpRequest? = nil

  /// Optional. Resource name of the trace associated with the log entry, if any.
  /// If this field contains a relative resource name, you can assume the name is
  /// relative to `//tracing.googleapis.com`. Example:
  /// `projects/my-projectid/traces/06796866738c859f2f19b7cfb3214824`
  public var trace: Swift.String = Swift.String()

  /// A unique ID for the log entry used for deduplication. If omitted,
  /// the implementation will generate one based on operation_id.
  public var insertId: Swift.String = Swift.String()

  /// A set of user-defined (key, value) data that provides additional
  /// information about the log entry.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Information about an operation associated with the log entry, if
  /// applicable.
  public var operation: LogEntryOperation? = nil

  /// Optional. Source code location information associated with the log entry,
  /// if any.
  public var sourceLocation: LogEntrySourceLocation? = nil

  /// The log entry payload, which can be one of multiple types.
  public var payload: OneOf_Payload? = nil

  /// Initialize a new instance of `LogEntry`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LogEntry().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case timestamp = "timestamp"
    case severity = "severity"
    case httpRequest = "httpRequest"
    case trace = "trace"
    case insertId = "insertId"
    case labels = "labels"
    case protoPayload = "protoPayload"
    case textPayload = "textPayload"
    case structPayload = "structPayload"
    case operation = "operation"
    case sourceLocation = "sourceLocation"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.timestamp = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .timestamp)
    self.severity = try container.decode(GoogleCloudLoggingType.LogSeverity.self, forKey: .severity)
    self.httpRequest = try container.decodeIfPresent(HttpRequest.self, forKey: .httpRequest)
    self.trace = try container.decode(Swift.String.self, forKey: .trace)
    self.insertId = try container.decode(Swift.String.self, forKey: .insertId)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.operation = try container.decodeIfPresent(LogEntryOperation.self, forKey: .operation)
    self.sourceLocation = try container.decodeIfPresent(
      LogEntrySourceLocation.self, forKey: .sourceLocation)

    var payload: OneOf_Payload? = nil
    let payloadCheckAndSet = {
      if payload != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'payload'"))
      }
      payload = $0
    }
    if let protoPayload = try container.decodeIfPresent(
      GoogleCloudWKT.`Any`?.self, forKey: .protoPayload)
    {
      try payloadCheckAndSet(.protoPayload(protoPayload))
    }
    if let textPayload = try container.decodeIfPresent(Swift.String.self, forKey: .textPayload) {
      try payloadCheckAndSet(.textPayload(textPayload))
    }
    if let structPayload = try container.decodeIfPresent(
      GoogleCloudWKT.Struct?.self, forKey: .structPayload)
    {
      try payloadCheckAndSet(.structPayload(structPayload))
    }
    self.payload = payload
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.timestamp, forKey: .timestamp)
    try container.encode(self.severity, forKey: .severity)
    try container.encode(self.httpRequest, forKey: .httpRequest)
    try container.encode(self.trace, forKey: .trace)
    try container.encode(self.insertId, forKey: .insertId)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.operation, forKey: .operation)
    try container.encode(self.sourceLocation, forKey: .sourceLocation)

    if let choice = self.payload {
      switch choice {
      case .protoPayload(let value):
        try container.encode(value, forKey: .protoPayload)
      case .textPayload(let value):
        try container.encode(value, forKey: .textPayload)
      case .structPayload(let value):
        try container.encode(value, forKey: .structPayload)
      }
    }
  }

  /// The log entry payload, which can be one of multiple types.
  public enum OneOf_Payload: Codable, Equatable, Sendable {
    /// The log entry payload, represented as a protocol buffer that is
    /// expressed as a JSON object. The only accepted type currently is
    /// [AuditLog][google.cloud.audit.AuditLog].
    indirect case protoPayload(GoogleCloudWKT.`Any`?)
    /// The log entry payload, represented as a Unicode string (UTF-8).
    case textPayload(Swift.String)
    /// The log entry payload, represented as a structure that
    /// is expressed as a JSON object.
    indirect case structPayload(GoogleCloudWKT.Struct?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v1.LogEntry"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
