// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// Represents error information for
/// [QuotaOperation][google.api.servicecontrol.v1.QuotaOperation].
///
/// [google.api.servicecontrol.v1.QuotaOperation]: <doc:QuotaOperation>
public struct QuotaError: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Error code.
  public var code: QuotaError.Code = QuotaError.Code()

  /// Subject to whom this error applies. See the specific enum for more details
  /// on this field. For example, "clientip:<ip address of client>" or
  /// "project:<Google developer project id>".
  public var subject: Swift.String = Swift.String()

  /// Free-form text that provides details on the cause of the error.
  public var description: Swift.String = Swift.String()

  /// Contains additional information about the quota error.
  /// If available, `status.code` will be non zero.
  public var status: GoogleRpc.Status? = nil

  /// Initialize a new instance of `QuotaError`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QuotaError().with { $0.code = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Error codes related to project config validations are deprecated since the
  /// quota controller methods do not perform these validations. Instead services
  /// have to call the Check method, without quota_properties field, to perform
  /// these validations before calling the quota controller methods. These
  /// methods check only for project deletion to be wipe out compliant.
  public enum Code: Codable, Equatable, Sendable {
    /// This is never used.
    case unspecified
    /// Quota allocation failed.
    /// Same as
    /// [google.rpc.Code.RESOURCE_EXHAUSTED][google.rpc.Code.RESOURCE_EXHAUSTED].
    case resourceExhausted
    /// Specified API key is invalid.
    case apiKeyInvalid
    /// Consumer cannot access the service because the service requires active
    /// billing.
    case billingNotActive
    /// Consumer's project has been marked as deleted (soft deletion).
    case projectDeleted
    /// Specified API Key has expired.
    case apiKeyExpired
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .resourceExhausted: return 8
      case .apiKeyInvalid: return 105
      case .billingNotActive: return 107
      case .projectDeleted: return 108
      case .apiKeyExpired: return 112
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "UNSPECIFIED"
      case .resourceExhausted: return "RESOURCE_EXHAUSTED"
      case .apiKeyInvalid: return "API_KEY_INVALID"
      case .billingNotActive: return "BILLING_NOT_ACTIVE"
      case .projectDeleted: return "PROJECT_DELETED"
      case .apiKeyExpired: return "API_KEY_EXPIRED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Code/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNSPECIFIED": self = .unspecified
      case "RESOURCE_EXHAUSTED": self = .resourceExhausted
      case "BILLING_NOT_ACTIVE": self = .billingNotActive
      case "PROJECT_DELETED": self = .projectDeleted
      case "API_KEY_INVALID": self = .apiKeyInvalid
      case "API_KEY_EXPIRED": self = .apiKeyExpired
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Code/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 8: self = .resourceExhausted
      case 105: self = .apiKeyInvalid
      case 107: self = .billingNotActive
      case 108: self = .projectDeleted
      case 112: self = .apiKeyExpired
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .resourceExhausted: return try container.encode(8)
      case .apiKeyInvalid: return try container.encode(105)
      case .billingNotActive: return try container.encode(107)
      case .projectDeleted: return try container.encode(108)
      case .apiKeyExpired: return try container.encode(112)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v1.QuotaError"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
